connector.name=iceberg

iceberg.catalog.type=jdbc

iceberg.jdbc-catalog.catalog-name=lakehouse

iceberg.jdbc-catalog.driver-class=org.postgresql.Driver

iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/metastore

iceberg.jdbc-catalog.connection-user=dba_admin

iceberg.jdbc-catalog.connection-password=Agent9-Backtalk6-Zestfully5-Luxury1-Calculus2

iceberg.jdbc-catalog.default-warehouse-dir=s3://lakehouse/warehouse

#iceberg.jdbc-catalog.schema-version=V1

fs.native-s3.enabled=true

s3.endpoint=http://minio:9000

s3.region=us-east-1

s3.path-style-access=true

s3.aws-access-key=admin_minio

s3.aws-secret-key=Grunt9-Relenting6-Hula5-Catcall9-Residue3