version: "3.9"

services:

  trino:
    image: trinodb/trino:477

    container_name: trino

    ports:
      - "8081:8080"

    volumes:
      - /home/luiz/Documentos/data-lakehouse-docker/data-lakehouse/portainer-stacks/stacks/trino/catalog:/etc/trino/catalog
      - trino_data:/var/trino

    restart: unless-stopped

    networks:
      - lakehouse

volumes:
  trino_catalog:
  trino_data:

networks:
  lakehouse:
    external: true