version: "3.9"

services:

  spark:
    image: apache/spark:4.0.0

    container_name: spark

    hostname: spark

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "4040:4040"
      - "7077:7077"

    volumes:
      - spark_data:/opt/spark/work-dir

    restart: unless-stopped

    networks:
      - lakehouse

  jupyter:
    image: jupyter/pyspark-notebook:latest

    container_name: jupyter

    ports:
      - "8888:8888"

    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "4f1c762d48f2a9fd5521e529efd1e6e9dc7d5105ce61649f"   # funciona como senha no login

    volumes:
      - ~/Documentos/data-lakehouse-docker/data-lakehouse/portainer-stacks/stacks/spark-jupyter/notebooks:/home/jovyan/work

    restart: unless-stopped

    networks:
      - lakehouse

volumes:
  spark_data:
  #jupyter_data:

networks:
  lakehouse:
    external: true